Validator Pricer Logic
PufferFinance/PufferPool pull request #260
Opened 2024-05-23 16:01 UTC by WalidOfNow

2024-05-27 21:11 UTC, JasonVranek requested changes

2024-05-27 21:11 UTC, JasonVranek commented on test/unit/ValidatorTicketPricer.t.sol
> +}
can we add some negative tests to make sure the roles are correct + fuzz test to make sure the toleranceBPs functions are correct?

2024-05-29 07:22 UTC, bxmmm1 commented on src/ValidatorTicketPricer.sol
> +        _setDailyMevPayouts(newValue);
Why would we want to have a setter that doesn't push the price to the oracle?

2024-05-29 07:32 UTC, bxmmm1 commented on src/ValidatorTicketPricer.sol
> +    uint16 internal _dailyMevPayoutsChangeToleranceBps;
Add a comment saying that a max tolerance is 655% because of the uint16

2024-05-29 07:37 UTC, bxmmm1 commented on src/ValidatorTicketPricer.sol
> +    uint128 internal _dailyMevPayouts;
We can pack everything in one slot
3x16 + 2x104 = 256

type(104).max = 20282409603651670423947251286015 = 20282409603651 ETH
I doubt that the daily rewards will go that high.

2024-05-29 07:44 UTC, bxmmm1 commented on src/ValidatorTicketPricer.sol
> +        uint256 newPrice =
I'd maybe cast variables to uint256 in this part, to be on the safe side

2024-05-29 07:50 UTC, bxmmm1 commented on test/unit/ValidatorTicketPricer.t.sol
> +    function testSetDailyMevPayoutsChangeToleranceBps() public {
all other tests use `test_...` can we convert these to that code style?

2024-05-29 08:09 UTC, bxmmm1 commented
We should update `foundry.toml` to use the latest Solidity version.

2024-06-01 06:24 UTC, bxmmm1 approved these changes

2024-06-01 06:24 UTC, merged